services:
  thinkarr:
    image: chrisrothwell/thinkarr:latest
    container_name: thinkarr
    environment:
      - PUID=1029 #CHANGE_TO_YOUR_UID
      - PGID=65536 #CHANGE_TO_YOUR_GID
      - TZ=Asia/Singapore #CHANGE_TO_YOUR_TZ
    volumes:
      - ./config:/config
    ports:
      - 3000:3000/tcp
    network_mode: plexbridge
    security_opt:
      - no-new-privileges:true
    restart: always